jackal_node:
  # Required topics for rosserial server (todo: specify these in code)
  require:
    publishers:
      - status
      - feedback
    subscribers:
      - cmd_drive

# Teleop configuration for PS3 Navigation joystick.
bluetooth_teleop:
  axis_linear: 1
  scale_linear: 0.4
  scale_linear_turbo: 2.0
  axis_angular: 0
  scale_angular: 0.4
  enable_button: 8
  enable_turbo_button: 10
  joy_node: 
    deadzone: 0.1
    autorepeat_rate: 20

jackal_velocity_controller:
  type: "diff_drive_controller/DiffDriveController"
  left_wheel: 'front_left_wheel_joint'
  right_wheel: 'front_right_wheel_joint'
  publish_rate: 50
  pose_covariance_diagonal: [0.001, 0.001, 1000000.0, 1000000.0, 1000000.0, 0.03]
  twist_covariance_diagonal: [0.001, 0.001, 1000000.0, 1000000.0, 1000000.0, 0.03]
  cmd_vel_timeout: 0.25

  # Velocity and acceleration limits
  # Whenever a min_* is unspecified, default to -max_*
  linear:
    x:
      has_velocity_limits    : true
      max_velocity           : 2.0   # m/s
      has_acceleration_limits: true
      max_acceleration       : 20.0   # m/s^2
  angular:
    z:
      has_velocity_limits    : true
      max_velocity           : 4.0   # rad/s
      has_acceleration_limits: true
      max_acceleration       : 25.0   # rad/s^2
